services:
  - type: web
    name: saleor-dashboard
    env: static
    buildCommand: chmod +x ./improved-build.sh && ./improved-build.sh
    staticPublishPath: ./
    envVars:
      - key: NODE_VERSION
        value: "20"
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
      - path: /*
        name: Cache-Control
        value: public, max-age=300
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
